# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches:
      - ssistoza/current
  workflow_dispatch:
jobs:
  dockerize:
    env:
      APP_NAME: ${{ secrets.APP_NAME }}
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_URL: ${{ secrets.APP_URL }}
      APP_DEBUG: ${{ secrets.APP_DEDUG }}
      DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      CACHE_DRIVER: ${{ secrets.CACHE_DRIVER }}
      QUEUE_CONNECTION: ${{ secrets.QUEUE_CONNECTION }}
      SESSION_DRIVER: ${{ secrets.SESSION_DRIVER }}
      SESSION_LIFETIME: ${{ secrets.SESSION_LIFETIME }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      MAIL_MAILER: ${{ secrets.MAIL_MAILER }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_ENCRYPTION: ${{ secrets.MAIL_ENCRYPTION }}
      MAIL_FROM_ADDRESS: ${{ secrets.MAIL_FROM_ADDRESS }}
      MAIL_FROM_NAME: ${{ secrets.MAIL_FROM_NAME }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify Environments are set.
        run: |
          if [[ -z "${{ secrets.APP_NAME }}" ]]; then
            echo "Environments are set"
          else
            echo "Environments are not set"
          fi
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ssistoza/envault:test
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
